version: '3.8'

services:
    api:
        build: .
        restart: always
        ports:
            - '3000:3000'
        env_file:
            - .env.docker
        depends_on:
            - db
            - redis

    db:
        image: postgres:14
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - '${DB_PORT}:5432'
        volumes:
            - db-data:/var/lib/postgresql/data

    redis:
        image: redis:7
        restart: always
        ports:
            - '${REDIS_PORT}:6379'

    api-test:
        build: .
        command: npm run test:docker
        env_file:
            - .env.test.docker
        depends_on:
            - db
            - redis
        tty: true
        stdin_open: true

volumes:
    db-data:
