services:
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api-dev
    env_file: [.env.docker]
    ports: ['3000:3000']
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_healthy
    profiles: ['dev']

  api-prod:
    build: .
    container_name: api-prod
    env_file: [.env.docker]
    ports: ['3000:3000']
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_healthy
    profiles: ['prod']

  postgres:
    image: postgres:14
    env_file: [.env.docker]
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports: ['${DB_PORT}:5432']
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports: ['${REDIS_PORT}:6379']
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres-data:
