version: '3.8'
services:
  weather:
    build:
      context: .
      dockerfile: apps/weather/Dockerfile
    env_file:
      - apps/weather/.env
    ports:
      - '5000:5000'
    depends_on:
      - redis

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    env_file:
      - apps/api-gateway/.env
    ports:
      - '3000:3000'
    depends_on:
      - weather

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
