services:
  weather:
    build:
      context: ../../
      dockerfile: apps/weather/Dockerfile
    container_name: weather
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  default:
    external:
      name: backend-net