export const TOKENS = {
  IWeatherApiProvider: Symbol.for('IWeatherApiProvider'),
  IWeatherApiClient: Symbol.for('IWeatherApiClient'),
  CacheServiceWeather: Symbol.for('CacheServiceWeather'),
  RedisTTL: Symbol.for('RedisTTL'),
  IRedisClient: Symbol.for('IRedisClient'),
  ICacheService: Symbol.for('ICacheService'),
  IWeatherMapper: Symbol.for('IWeatherMapper'),
  WeatherService: Symbol.for('WeatherService'),
  WeatherController: Symbol.for('WeatherController'),
  WeatherDigestJob: Symbol.for('WeatherDigestJob'),
  IEmailTransport: Symbol.for('IEmailTransport'),
  IEmailService: Symbol.for('IEmailService'),
  SubscriptionService: Symbol.for('SubscriptionService'),
  SubscriptionController: Symbol.for('SubscriptionController'),
  ISubscriptionRepository: Symbol.for('ISubscriptionRepository'),
  ILogger: Symbol.for('ILogger'),
  ErrorHandlerMiddleware: Symbol.for('ErrorHandlerMiddleware'),
  ICacheMetricService: Symbol.for('ICacheMetricService'),
} as const;
