export const TOKENS = {
  IWeatherApiClient: Symbol.for('IWeatherApiClient'),
  CacheServiceWeather: Symbol.for('CacheServiceWeather'),
  RedisTTL: Symbol.for('RedisTTL'),
  IRedisClient: Symbol.for('IRedisClient'),
  WeatherMapper: Symbol.for('WeatherMapper'),
  WeatherService: Symbol.for('WeatherService'),
  WeatherController: Symbol.for('WeatherController'),
  WeatherDigestJob: Symbol.for('WeatherDigestJob'),
  IMailTransport: Symbol.for('IMailTransport'),
  IMailService: Symbol.for('IMailService'),
  SubscriptionService: Symbol.for('SubscriptionService'),
  SubscriptionController: Symbol.for('SubscriptionController'),
  ISubscriptionRepository: Symbol.for('ISubscriptionRepository'),
} as const;
