export const GrpcClientDiTokens = {
  EMAIL_SERVICE_GRPC_CLIENT: Symbol.for('EMAIL_SERVICE_GRPC_CLIENT'),
  NOTIFICATION_SERVICE_GRPC_CLIENT: Symbol.for('NOTIFICATION_SERVICE_GRPC_CLIENT'),
  SUBSCRIPTION_SERVICE_GRPC_CLIENT: Symbol.for('SUBSCRIPTION_SERVICE_GRPC_CLIENT'),
  WEATHER_SERVICE_GRPC_CLIENT: Symbol.for('WEATHER_SERVICE_GRPC_CLIENT'),
};
