export enum EmailType {
  SUBSCRIPTION_CONFIRMATION = 'SUBSCRIPTION_CONFIRMATION',
  CONFIRMED_SUBSCRIPTION = 'CONFIRMED_SUBSCRIPTION',
  UNSUBSCRIPTION_GOODBYE = 'UNSUBSCRIPTION_GOODBYE',
  DAILY_DIGEST = 'DAILY_DIGEST',
  HOURLY_DIGEST = 'HOURLY_DIGEST',
}
