services:
  notification:
    build:
      context: ../../
      dockerfile: apps/notification/Dockerfile
    container_name: notification
    env_file:
      - .env
    ports:
      - '6600:6600'

networks:
  default:
    external:
      name: backend-net