services:
  api-gateway:
    build:
      context: ../../
      dockerfile: apps/api-gateway/Dockerfile
    container_name: api-gateway
    env_file:
      - .env
    ports:
      - '3000:3000'

networks:
  default:
    external:
      name: backend-net