services:
  email:
    build:
      context: ../../
      dockerfile: apps/email/Dockerfile
    container_name: email
    env_file:
      - .env
    ports:
      - '8888:8888'
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

networks:
  default:
    external:
      name: backend-net