name: Integration Tests

on:
  push:
    paths:
      - 'src/**'
      - 'docker-compose.yml'
      - 'docker-compose.test.yml'
      - '.github/workflows/integration-tests.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'docker-compose.yml'
      - 'docker-compose.test.yml'
      - '.github/workflows/integration-tests.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      APP_BASE_URL: http://localhost:3000
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      WEATHER_BASE_URL: https://api.weatherapi.com/v1
      OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
      OPENWEATHERMAP_BASE_URL: https://api.openweathermap.org/data/2.5
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_NAME: weatherdb
      TEST_DB_NAME: weatherdb
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_TTL: 60
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 465
      MAIL_SECURE: true
      MAIL_USER: ${{ secrets.MAIL_USER }}
      MAIL_PASS: ${{ secrets.MAIL_PASS }}
      MAIL_FROM: Weather API <no-reply@weatherapi.app>

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create .env.test.docker from secrets
        run: |
          cat <<EOF > .env.test.docker
          PORT=3000
          WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}
          WEATHER_BASE_URL=${{ env.WEATHER_BASE_URL }}
          OPENWEATHERMAP_API_KEY=${{ secrets.OPENWEATHERMAP_API_KEY }}
          OPENWEATHERMAP_BASE_URL=${{ env.OPENWEATHERMAP_BASE_URL }}

          DB_USER=${{ env.DB_USER }}
          DB_PASSWORD=${{ env.DB_PASSWORD }}
          DB_HOST=postgres-test
          DB_PORT=5432
          DB_NAME=${{ env.DB_NAME }}
          TEST_DB_NAME=${{ env.TEST_DB_NAME }}
          
          MAIL_HOST=${{ env.MAIL_HOST }}
          MAIL_PORT=${{ env.MAIL_PORT }}
          MAIL_SECURE=${{ env.MAIL_SECURE }}
          MAIL_USER=${{ secrets.MAIL_USER }}
          MAIL_PASS=${{ secrets.MAIL_PASS }}
          MAIL_FROM=${{ env.MAIL_FROM }}
          APP_BASE_URL=${{ env.APP_BASE_URL }}
          
          REDIS_HOST=redis-test
          REDIS_PORT=6379
          REDIS_TTL=${{ env.REDIS_TTL }}
          EOF

      - name: Start Postgres & Redis
        run: |
          docker compose -f docker-compose.test.yml up -d postgres-test redis-test
          docker ps

      - name: Wait for Postgres to be healthy
        run: |
          until docker compose -f docker-compose.test.yml exec -T postgres-test pg_isready -U $DB_USER; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
          echo "PostgreSQL is ready!"

      - name: Wait for Redis to be healthy
        run: |
          until docker compose -f docker-compose.test.yml exec -T redis-test redis-cli ping | grep PONG; do
            echo "Waiting for Redis to be ready..."
            sleep 2
          done
          echo "Redis is ready!"

      - name: Run integration tests
        run: npm run test:int

      - name: Upload integration test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: test-results/integration

      - name: Tear down Docker Compose
        if: always()
        run: docker compose -f docker-compose.test.yml down --volumes
